name: Build MSI on Issue Open

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Install dependencies with Bun
        run: |
          bun install

      - name: Build frontend
        run: |
          bun run build

      - name: Install Tauri CLI
        run: |
          bun add -d @tauri-apps/cli
          bunx tauri info

      - name: Build Tauri app (.msi)
        run: |
          bunx tauri build --target x86_64-pc-windows-msvc

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: src-tauri/target/release/bundle/msi/
